export const COLORS = {
    flashGreen: 'rgba(0, 255, 0, 0.3)',
    flashRed: 'rgba(255, 0, 0, 0.3)',
    transparent: 'transparent',
    positiveBackground: '#4CAF50',
    negativeBackground: '#F44336',
    white: 'white',
    black: '#000',
    border: 'rgba(0,0,0,0.02)',
    textPrimary: '#1a1a1a',
    textSecondary: '#333',
    backgroundLight: '#f8f9fc',
    borderLight: 'rgba(0,0,0,0.04)',
    textLabel: '#8e9aaf',
    textValue: '#2d3748',
    positiveText: 'green',
    negativeText: 'red',
    shadow: '#000',
    backgroundApp: '#f8f9fa',
    borderHeader: '#ebebeb',
    statusPill: '#f0f0f0',
    textStatus: '#666',
    statusConnected: 'green',
    statusConnecting: 'orange',
    statusDisconnected: 'red',
};
